name: "Roya's Culinary Journey"
favicon: null
layout_spectrum: 0.75899
typography_spectrum: 0.68527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8573b'
    - '#57302c'
    - '#bb896b'
    - '#fefffd'
    - '#65b155'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
