name: "Roya's Culinary Journey"
favicon: null
layout_spectrum: 0.7278657669667155
typography_spectrum: 0.5611719847656786
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8650422990322113
  lightness: 0.7536593182012439
  saturation: 0.49070397368632257
  rhythmicContrast: 0.3866018441040069
purpose: []
